### ISSUE TITLE
Disable or end infinite mob spawning.

### ISSUE THREAD

**Issue by DamienVortex** [frqnny/mostructures#66] opened 2022-04-26 04:16 UTC
In the floating castle is there something you gotta do to stop the mob spawning or a config or something where you limit the spawning? They spawn infinitely and it's kinda dumb.

**Comment by frqnny** [comment] 2022-05-01 19:03
Light should stop them from spawning. Also, since it is a dungeon, the spawner is used to spawn a lot (20 or 30) in max. I'll check it to see if it really spawns "infinitely" or if it is working as intended.

**Comment by frqnny** [comment] 2022-05-03 21:51
Fixed in dev

**Closed as completed by frqnny** 2022-05-03 21:51 UTC
Labels: bug
