### ISSUE TITLE
Game Freezing.

### ISSUE THREAD

**Issue by CyberFeast2K** [frqnny/mostructures#33] opened 2021-04-15 00:41 UTC
My game keeps on freezing every time I go near the villager market, it doesn’t give me a crash log and when I check my game logs everything looks fine. And from what I know this only happens when I go near the villager market I’ve gone near the hot air ballon and I haven’t crashed.

**Comment by frqnny** [comment] 2021-04-15 01:00
Well, can you give me the log anyway, please? I can't decipher the problem from just this. I don't know the MC version nor what mod version you're using, and a log could solve those problems easily.

**Comment by CyberFeast2K** [comment] 2021-04-15 02:08
Oh sorry, well the minecraft version is 1.16.5 and the mod version is mostructures-1.1.1+mc.1.16.5.jar and the https://gist.github.com/CyberFeast2K/9b400f5403153d24637a2830fda40e51

**Comment by frqnny** [comment] 2021-04-15 02:09
Awesome, thanks!

**Comment by frqnny** [comment] 2021-04-15 02:10
Uh, wrong log. This is the last line, looks like it didn't get past even launching. 
`21:52:21] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'xaerominimap': [21.5.0 at /Users/kane/Library/Application%20Support/minecraft/mods/Xaeros_Minimap_21.5.0_Fabric_1.16.5.jar], [21.6.0 at /Users/kane/Library/Application%20Support/minecraft/mods/Xaeros_Minimap_21.6.0_Fabric_1.16.5.jar]
	at net.fabricmc.loader.discovery.ModCandidateSet.toSortedSet(ModCandidateSet.java:89) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:101) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]`

**Comment by frqnny** [comment] 2021-05-27 20:55
Since you haven't updated this in a while, I am closing this.

**Closed as completed by frqnny** 2021-05-27 20:55 UTC
Labels: bug, question

**Comment by Fade-Alchemist** [comment] 2021-06-09 07:02
I can confirm this is still a problem, I had to disable the Market- It loads in glitched, and if you approach the game will crash. The same happens with some variants of the abandoned farm as well. 
[2021-06-09-2.log.gz](https://github.com/frqnny/mostructures/files/6621695/2021-06-09-2.log.gz)
The below is the abandoned farm version that crashes the game
![2021-06-09_02 06 24](https://user-images.githubusercontent.com/29619427/121309309-a65b9900-c8c7-11eb-80eb-4f4479daa16f.png)
